server:
    port: 8088
spring:
    jmx:
        enabled: false
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher  # 关键：适配Swagger 2.9.2

    servlet:
        multipart:
            # 最大上传单文件大小
            max-file-size: 10MB
            # 最大上传总大小
            max-request-size: 10MB
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://58.87.103.30:3306/yuxi_admin?serverTimezone=GMT%2B8
        username: tiankai
        password: Qq133242
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl